name: Cake-Bnb-Alert

# on:
#   push:
#   schedule:
#     - cron: '0 * * * *'
#   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Run Python Script
      env:
        FTX_KEY: ${{ secrets.FTX_KEY }}
        FTX_SECRET: ${{ secrets.FTX_SECRET }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_DEBUG_GROUP_ID: ${{ secrets.TG_DEBUG_GROUP_ID }}
        TG_GROUP_ID: ${{ secrets.TG_GROUP_ID }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        TG_USER_NAME: ${{ secrets.TG_USER_NAME }}
        EMERGENCY_RATE: ${{ secrets.EMERGENCY_RATE }}
        LOW_RATE: ${{ secrets.LOW_RATE }}
        HIGH_RATE: ${{ secrets.HIGH_RATE }}
        SEND_ENV: ${{ secrets.SEND_ENV }}
      run: |
        python main.py